# Generated by Django 3.2.6 on 2021-08-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_bookcollection_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcollection',
            name='email',
        ),
        migrations.AddField(
            model_name='bookcollection',
            name='genre',
            field=models.CharField(default='genre', max_length=100),
        ),
    ]
